// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_chesssquare.cpp"
#include "EWIEGA46WW/moc_game.cpp"
#include "EWIEGA46WW/moc_history.cpp"
#include "EWIEGA46WW/moc_home.cpp"
#include "EWIEGA46WW/moc_login.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
